Attempt at working around flakiness in Windows workflow (#1570)
That mv operation fails from time to time for unknown reasons.

diff --git a/.github/workflows/ci-toolchain.yml b/.github/workflows/ci-toolchain.yml
--- a/.github/workflows/ci-toolchain.yml
+++ b/.github/workflows/ci-toolchain.yml
@@ -60,8 +60,10 @@ jobs:
       run: ./bin/alr -d -n printenv || ./bin/alr -n -v -d printenv
 
     - shell: bash
-      run: mv ./bin ./bin-old
-      # Windows doesn't allow to replace a running exe so the next command fails otherwise
+      run: mv ./bin ./bin-old || { sleep 5s && sudo mv ./bin ./bin-old; }
+      # Windows doesn't allow to replace a running exe so the next command
+      # fails otherwise. Also, this mv fails sometimes so we try twice JIC.
+
 
     - name: SELF-BUILD
       run: ./bin-old/alr -d -n build
