Optimization: filter out seen linked deps

diff --git a/.github/workflows/ci-toolchain.yml b/.github/workflows/ci-toolchain.yml
--- a/.github/workflows/ci-toolchain.yml
+++ b/.github/workflows/ci-toolchain.yml
@@ -64,7 +64,13 @@ jobs:
       run: ./bin/alr -d -n update
 
     - name: Show dependencies/pins
-      run: ./bin/alr -d -n -q with --solve || ./bin/alr -n -v -d with --solve
+      run: |
+        ./bin/alr -d -n -q with --solve || ./bin/alr -n -v -d with --solve
+        if ./bin/alr -n -q with --solve | grep -q 'Dependencies (missing):'; then
+          echo "SELF-SOLVING FAILED, complete log follows:"
+          ./bin/alr -n -vv update
+          exit 1
+        fi
 
     - name: Show build environment, with debug fallback
       run: ./bin/alr -d -n printenv || ./bin/alr -n -v -d printenv
